# Generated by Django 5.1.5 on 2025-01-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(max_length=200),
        ),
    ]
