# Generated by Django 5.1.5 on 2025-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal_api', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
