# Generated by Django 5.1.5 on 2025-01-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal_api', '0003_alter_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='difference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
