# Generated by Django 5.1.5 on 2025-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal_api', '0004_table_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
